language: java
jdk: oraclejdk8
notifications:
  email: false
  slack:
    secure: E+yvYCCZ+xgyGKCj2/8Xy+hC2fX7ADemnrVY8T8AiIkl+4LR+oSDHbunIY3egsLVWrLZFsy6w/4Da7WKkHFb32VGUyrm99Z2VXQM3QsvDYR74EO1iZPAlz191nSxA01iZV5cr0nDoCUiuHDhDzWAn434hZflOhebPUN8t2yZ2aJVmEf/XVuB6YmDcyydJvPFkZhs9FV9/E+HxJW1B+/6eICUXxl779aZ4zyxZQSQBPc7oxC7+jeTWRPRsw1gZePlWXONUfpmfVTQGEh9bN0qtPhUxzTr+qJI3LjckmGyWnvW5UCE1bUrykmFaZCHka4UO2Mlfe+LXU82o6alWxtP3cF/HXegoIGR/rRSRvMB3bYBJpEfxxVWotL/RmSEwoxI5ytupKQ9v4MpmAcxpLPsKkIwk5JoHR76aEwxX6QJz7OIJb4MLeWX8BeIb2PEhFolSqLpNvzruDEu6vy/5O8835L1GgZ4CTpFlpm79R91JtYJ+sagfYn6B0ldag+uDXacQdi35nTZz1hime5IV9viV8kFKMIyL/lR466kZ4m7spT0+DUCBaGkMBMoRSY94QNyvGqDn+KjR7DJErg00+aMGTbI2erxaG4pU/jD19ym5K3g915reVoCVAi3Dx+t/P4m9S3BC0uiz2w1XEIkDxfDbAt0fURxkZy4JLd+vfDsLIA=
